services:
  gophermart:
    environment:
      DATABASE_URI: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      PGPASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

  accrual:
    build: cmd/accrual
    restart: unless-stopped
    ports:
      - '${ACCRUAL_EXTERNAL_PORT:-8081}:${ACCRUAL_INTERNAL_PORT:-8081}'
    env_file:
      - .env
    environment:
      RUN_ADDRESS: '0.0.0.0:${ACCRUAL_INTERNAL_PORT:-8081}'
      DATABASE_URI: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/accrual?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
    driver: local
